### PR TITLE
Beautification

### PR DESCRIPTION
**Pull request by Harlantr**
Designed similar to Google Maps. Mostly was an experiment in Material Design.

### CODE REVIEW

**Comment by tuchfarber** [comment]
Line 29 of your index.html doesn't work correctly. The reason I had nested spans for opening hours is because the first one checks if opening hours data exists. If it does, the inner one checks if it's open now. With just the outer statement (what you changed it to), it will display "Open Now!" anytime the location has it's opening hours posted, whether is open now or not.

**Comment by tuchfarber** [comment]
Also, is there a reason for the button sized gap between the Veto button and the right side of the list area?

**Comment by Harlantr** [comment]
Ah, I didn't know that. Since I couldn't test with the API locally, I didn't notice it not working. It just looked a little redundant; I didn't know it was necessary.

And are you looking at the desktop or mobile version? I don't think I saw a big gap when I was testing locally. I'll check it out again.

**Comment by tuchfarber** [comment]
gap This is what I'm seeing

**Comment by Harlantr** [comment]
Oh, ok. Are you wanting to right-justify it?

**Comment by Harlantr** [comment]
Keep the change, you filthy animal.

**Pull request merged**
